#!/usr/bin/env php

<?php

// 1. Установить базовый путь

use Somecode\Framework\Console\Kernel;

define('BASE_PATH', dirname(__FILE__));

// 2. Добавить autoloader

require_once BASE_PATH.'/vendor/autoload.php';

// 3. Добавить контейнер

/** @var \League\Container\Container $container */
$container = require BASE_PATH.'/config/services.php';

// 4. Получить Kernel консоли из контейнера

$kernel = $container->get(Kernel::class);

// 5. Вызвать метод handle в Kernel, вернуть код статуса консольного приложения

$status = $kernel->handle();

// 6. Выйти с этим статусом.

exit($status);
